name: From scratch on Ubuntu server

on:
  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

  push: ~

jobs:
  yolo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build test container
        run: docker build -t ubuntu_server .

      - name: Make yolo
        run: docker run --rm -v "`pwd`:/workdir" -w /workdir ubuntu_server make yolo
